name: Test CI

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check for flake configurations
        run: nix flake check --all-systems --show-trace

      - name: Compile css
        run: nix-shell --run "tailwindcss -i ./style/input.css -o ./style/output.css"

      - name: Compile website
        run: nix-shell --run "trunk build --release"

      - name: Build via Nix
        run: nix build
